service:
  name: retro-issue-slack-bot
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish

provider:
  name: aws
  runtime: nodejs8.10
  environment: ${file(./env.yml):${opt:stage, self:provider.stage}}
  region: ap-northeast-1

functions:
  slack-events:
    timeout: 5
    handler: src/events.slackEventHandler
    events:
      - http:
          path: slack-events
          method: post
  slack-events-reactor:
    timeout: 30
    handler: src/events.slackReactor
    events:
        - sns: arn:aws:sns:${self:provider.region}:872242893131:${opt:stage, 'dev'}-retro-issue-slack-notify

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    port: 3001
  webpack:
    includeModules: true
  